projects/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# media -> static, settings import 추가
from django.conf.urls.static import static
from django.urls import path, include, re_path
from .views import IndexMain
from django.conf import settings
from django.views.static import serve

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexMain.as_view(), name='index'),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls')),
    re_path(r'^media/(?P<path>.)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^staticfiles/(?P<path>.)$', serve,{'document_root': settings.STATIC_ROOT}),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #media 경로추가

projects/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 글 목록 조회
    path('',views.Index.as_view(), name='list'),
    
    # 글 작성
    path('write/',views.Write.as_view(), name='write'),
    
    # 글 상세 조회
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    
    # 글 수정
    path('detail/<int:pk>/edit/', views.Update.as_view(), name='edit'),
    
    # 글 삭제
    path('detail/<int:pk>/delete/', views.Delete.as_view(), name='delete'),
    
    # 코멘트 작성
    path('detail/<int:pk>/comment/write/', views.CommentWrite.as_view(), name='cm-write'),
    
    # 코멘트 삭제
    path("detail/comment/<int:pk>/delete/", views.CommentDelete.as_view(), name='cm-delete'),
    
    # 태그 작성
    path("detail/<int:pk>/hashtag/write/", views.HashTagWrite.as_view(), name='tag-write'),
    
    # 태그 삭제
    path("detail/<int:pk>/hashtag/delete/", views.HashTagDelete.as_view(), name='tag-delete'),

    # 태그 검색
    path("search/<str:tag>", views.PostSearch.as_view(), name='post-search'),
]

projects/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # 회원가입
    path('register/', views.Registration.as_view(), name='register'),
    
    # 로그인
    path('login/', views.Login.as_view(), name='login'),
    
    # 로그아웃
    path('logout/', views.Logout.as_view(), name='logout'),
]

projects/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 부트스트랩 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/post.css' %}">
    <link rel="stylesheet" href="{% static 'css/user.css' %}">
    <title>
        {% block title %} {{ title }} {% endblock %}
    </title>
</head>
<body class="d-flex flex-column min-vh-100" >
    {% include 'navbar.html' %}
    <div class="container">
        <div class="user-status">
            {% if user.is_authenticated %}
                <p>환영합니다, <strong>{{ user.email }}</strong>님</p>
            {% else %}
                <p>원활한 서비스 이용을 위해 로그인 해주세요</p>
            {% endif %}
        </div>
        <!-- 렌더링 화면 -->
        {% block content %}
        {% endblock %}
    </div>
    <!-- footer -->
    <div class="mt-auto" id="footer">Copyright 2023. All rights reserved.</div>
    <!-- //footer -->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

projects/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column bd-highlight">
    <div class="p-2 bd-highlight">
        <h1 class="main-title">
            {{ title }}
        </h1>
    </div>
    <div class="p-2 bd-highlight">
        <a class="main-button btn" href="{% url 'blog:list' %}">BLOG</a>
    </div>
    <div class="p-2 bd-highlight">
        <a class="main-button btn" href="{% url 'users:register' %}">REGISTER</a>
    </div>
    <div class="p-2 bd-highlight">
        <a class="main-button btn" href="{% url 'users:login' %}">LOGIN</a>
    </div>
</div>

{% endblock %}

projects/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">
            <img class="m-2" src="/static/img/message.png" alt="" width="30" height="24" class="d-inline-block align-text-top">My blog
        </a>
        <button class="navbar-toggler" type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- 로그인 된 사람만 로그아웃, 글 작성 버튼 보임 -->
                {% if user.is_authenticated %}
                <li>
                    <a class="nav-link" href="{% url 'blog:write' %}" class="btn">WRITE<img src="/static/img/write.png" alt="" width="20" height="24" class="d-inline-block align-text-top"></a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'users:logout' %}" class="btn">Logout<img src="/static/img/logout.png" alt="" width="20" height="24" class="d-inline-block align-text-top"></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}" class="btn">Register</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'users:login' %}" class="btn">Login<img src="/static/img/login.png" alt="" width="20" height="24" class="d-inline-block align-text-top"></a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>