projects/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# media -> static, settings import 추가
from django.conf.urls.static import static
from django.urls import path, include, re_path
from .views import IndexMain
from django.conf import settings
from django.views.static import serve

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexMain.as_view(), name='index'),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls')),
    re_path(r'^media/(?P<path>.)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^staticfiles/(?P<path>.)$', serve,{'document_root': settings.STATIC_ROOT}),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #media 경로추가

projects/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 글 목록 조회
    path('',views.Index.as_view(), name='list'),
    
    # 글 작성
    path('write/',views.Write.as_view(), name='write'),
    
    # 글 상세 조회
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    
    # 글 수정
    path('detail/<int:pk>/edit/', views.Update.as_view(), name='edit'),
    
    # 글 삭제
    path('detail/<int:pk>/delete/', views.Delete.as_view(), name='delete'),
    
    # 코멘트 작성
    path('detail/<int:pk>/comment/write/', views.CommentWrite.as_view(), name='cm-write'),
    
    # 코멘트 삭제
    path("detail/comment/<int:pk>/delete/", views.CommentDelete.as_view(), name='cm-delete'),
    
    # 태그 작성
    path("detail/<int:pk>/hashtag/write/", views.HashTagWrite.as_view(), name='tag-write'),
    
    # 태그 삭제
    path("detail/<int:pk>/hashtag/delete/", views.HashTagDelete.as_view(), name='tag-delete'),

    # 태그 검색
    path("search/<str:tag>", views.PostSearch.as_view(), name='post-search'),
]

projects/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    imgfile = models.ImageField(null=True, upload_to="", blank=True) # 이미지 컬럼추가
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    hit = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.title
    
    @property
    def update_counter(self):
        self.hit += 1
        self.save()
        

class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.content


class HashTag(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    def __str__(self):
        return self.name 

projects/blog/forms.py
from django import forms
from .models import Post, Comment, HashTag

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title','content', 'imgfile']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10, 'cols':'35'}),
        }
        labels = {
            'title': '제목',
            'content': '내용',
            'imgfile': '이미지'
        }


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(
                attrs={'rows': '3', 'cols': '110', 'placeholder': '댓글을 입력해주세요.', 'style': 'resize:none'})
        }
        

class HashTagForm(forms.ModelForm):
    
    class Meta:
        model = HashTag
        fields = ['name']

projects/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from .models import Post, Comment, HashTag
from .forms import PostForm, CommentForm, HashTagForm
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# 글 목록 조회
class Index(View):
    def get(self, request):
        # Post 모델에서 전체 객체 가져오기
        post = Post.objects.all()
        # get 방식으로 호출된 url에서 page값을 가져올 때 사용 page값없이 호출된 경우에는 디폴트로 1이라는 값을 설정
        page = request.GET.get('page',1)
        # 첫번째 파라미터 post 게시물 전체를 의미하는 데이터, 두번째 파라미터는 5 페이지당 보여줄 게시물의 개수
        paginator = Paginator(post,5)
        # paginator을 이용하여 요청된 페이지(page)에 해당되는 페이징 객체(page_obj)생성 -> 장고 내부적으로 데이터 전체를 조회하지 않고 해당 페이지의 데이터만 조회하도록 쿼리가 변경
        page_obj = paginator.get_page(page)
        
        context = {
            # posts는 page_obj 즉 5페이지의 데이터 조회
            'title': 'Blog',
            'posts': page_obj,
            'post_obj': post,
        }
        return render(request, 'blog/post_list.html', context)


# 글 작성
class Write(LoginRequiredMixin, View):
    def get(self, request):
        form = PostForm()
        context = {
            'title': 'Blog',
            'form': form,
        }
        return render(request, 'blog/post_form.html', context)
    
    def post(self,request):
        form = PostForm(request.POST, request.FILES) # files는 따로 request의 files로 속성을 지정
        
        if form.is_valid():
            post = form.save(commit=False)
            post.writer = request.user
            post.save()
            return redirect('blog:list')
        
        context = {
            'form' : form,
        }
        return render(request, 'blog/post_form.html', context)


# 글 상세 조회
class DetailView(View):
    
    def get(self, request, pk):
        post = Post.objects.prefetch_related('comment_set', 'hashtag_set').get(pk=pk)
        post.update_counter # 조회수 올리기
        
        comments = post.comment_set.all()
        hashtags = post.hashtag_set.all()
        
        comment_form = CommentForm()
        hashtag_form = HashTagForm()
        
        context = {
            'title': 'Blog',
            'post_id' : pk,
            'post_title': post.title,
            'post_writer': post.writer,
            'post_content': post.content,
            'post_created_at': post.created_at,
            'post_hit': post.hit,
            'comments': comments,
            'hashtags': hashtags,
            'comment_form': comment_form,
            'hashtag_form': hashtag_form,
            'post_imgfile' : post.imgfile
        }
        
        return render(request, 'blog/post_detail.html', context)
        

# 글 수정
class Update(View):
    def get(self, request, pk):
        # 조건을 만족하는 object가 있으면 해당 object를 리턴하고, 없으면 404처리 첫번째 인자 Post에서 두번째 인자 해당 아이디의 post객체를 가져오는 것 
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(initial={'title': post.title, 'content': post.content})
        context = {
            'title':'Blog',
            # post객체 값을 넘겨주어야 더 정확함
            'post': post,
            'form': form,
        }
        return render(request, 'blog/post_edit.html',context)
    
    def post(self,request, pk):
        # 수정 할 객체를 불러옴
        post = get_object_or_404(Post, pk=pk)
        # 새롭게 사용자에게 수정 할 내용을 입력 받음
        form = PostForm(request.POST, request.FILES, instance=post)
        
        if form.is_valid():
            # 수정 할 객체(post)를 수정할 값(form으로 받은 데이터)으로 새롭게 넣어준 뒤(title,content)만 수정 가능하도록 할 것이기에 두 가지만 받음 -> 새롭게 수정된 객체를 다시 저장 -> 내용을 디비에 저장
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.save()
            return redirect('blog:detail', pk=pk)
            # DetailView.get(self,request,post_id)로 정의했기 때문에 post_id로 attribute 선언해야함
        
        context = {
            'title': 'Blog',
            'form': form,
            'post': post,
        }
        return render(request, 'blog/post_edit.html', context)


# 글 삭제
class Delete(View):
    
    def post(self,request,pk):
        post = get_object_or_404(Post, pk=pk)
        post.delete()
        return redirect('blog:list')
    

# 댓글 작성
class CommentWrite(LoginRequiredMixin, View):
    def post(self, request, pk):
        form = CommentForm(request.POST)
        post = get_object_or_404(Post, pk=pk)
        
        if form.is_valid():
            content = form.cleaned_data['content']
            writer = request.user
            
            try:
                comment = Comment.objects.create(post=post, content=content, writer=writer)
            except ObjectDoesNotExist as e:
                print('Post does not exist', str(e))
            
            except ValidationError as e:
                print('Validation error occurred', str(e))
            
            return redirect('blog:detail', pk=pk)
    
        hashtag_form = HashTagForm()
        
        context = {
            'title': 'Blog',
            'post_id' : pk,
            'comments' : post.comment_set.all(),
            'hashtags' : post.hashtag_set.all(),
            'comment_form' : form,
            'hashtag_form': hashtag_form
        }
        return render(request, 'blog/post_detail.html', context)


# 댓글 삭제
class CommentDelete(View):
    def post(self, request, pk): # comment_id
        comment = get_object_or_404(Comment, pk=pk)
        post_id = comment.post.id
        comment.delete()
        return redirect('blog:detail', pk=post_id)


# 해시태그 작성
class HashTagWrite(LoginRequiredMixin, View):
    def post(self, request, pk): # post_id
        form = HashTagForm(request.POST)
        post = get_object_or_404(Post, pk=pk)
        
        if form.is_valid(): 
            name = form.cleaned_data['name']
            writer = request.user
            
            try:
                hashtag = HashTag.objects.create(post=post, name=name, writer=writer)
                
            except ObjectDoesNotExist as e:
                print('Post does not exist.', str(e))
                
            except ValidationError as e:
                print('Validation error occurred', str(e))
            
            return redirect('blog:detail', pk=pk)
        
        comment_form = CommentForm()
        
        context = {
            'title': "Blog",
            'post': post,
            'comments': post.comment_set.all(),
            'hashtags': post.hashtag_set.all(),
            'comment_form': comment_form,
            'hashtag_form': form
        }
        return render(request,'blog/post_detail.html',context)


# 해시태그 삭제
class HashTagDelete(View):
    def post(self, request, pk): # hashtag_id
        hashtag = get_object_or_404(HashTag, pk=pk)
        post_id = hashtag.post.id
        hashtag.delete()
        return redirect('blog:detail', pk=post_id)
    

# 해시태그 검색
class PostSearch(View):
    def get(self, request, tag):
        print(f'request.GET: {request.GET}')
        posts = Post.objects.prefetch_related(
            'hashtag_set').filter(hashtag__name=tag)
        print(f'tag: {tag}')
        context = {
            'posts': posts,
        }
        return render(request, 'blog/post_list.html', context)

projects/blog/templates/blog/form_error.html
<!-- form error 출력 -->

<div class="alert alert-danger">
    {{ form }}
</div>

projects/blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content%}
<div class="container">
    <div>
        <!-- 게시판 목록 버튼 -->
        <button class="index-board"><a href="{% url 'blog:list' %}" class="btn"><img src="/static/img/index.png" alt="" width="30" height="24">목록</a></button>
        <!-- 글 수정버튼 -->
        <section class="detail-post-button gap-1">
            {% if post_writer == request.user %}
                <span><a class="btn btn-outline-secondary"href="{% url 'blog:edit' pk=post_id %}">수정</a></span>
                <!-- 글 삭제버튼 -->
                <span><form action="{% url 'blog:delete' pk=post_id %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-outline-secondary "type="submit" value="삭제">
                </form></span>
            {% endif %}
        </section>
    </div>
        <!-- 글 상세 화면 -->
        <div class="detail-title">
            <h2>{{ post_title }}</h2>
            <br>
            <section class="detail-information">
                <span><img src="/static/img/people.png" width="22" height="20" alt="">{{ post_writer }} | </span>
                <span><img src="/static/img/counter.png" width="22" height="20" alt="">{{ post_hit }} | </span>
                <span><img src="/static/img/time.png" width="22" height="20" alt="">{{ post_created_at|date:"Y-m-d" }}</span>
            </section>
        </div>
        <div class="d-flex justify-content-center">
            {% if post_imgfile %}
                    <div class="p-2">
                        <img src="{{ post_imgfile.url }}" alt="게시물사진" width="700px" height="500px">
                    </div>
                    {% endif %}
                </div>
                <p class="mt-5 mb-5">{{ post_content }}</p>
    
                <!-- hashtags -->
                <h3><img src="/static/img/hashtag2.png" alt="" width="30" height="30">HashTag</h3>
                <form action="{% url 'blog:tag-write' pk=post_id %}" method="post">
                    {% csrf_token %}
                    {% if hashtag_form.errors %}
                        {% with form=hashtag_form %}
                            {% include 'blog/form_error.html' %}
                        {% endwith %}
                    {% else %}
                        {{ hashtag_form.name }}
                    {% endif %}
                    <input class="btn btn-outline-secondary btn-sm" type="submit" value="등록">
                </form>
            
                {% if hashtags %}
                    <ul class="list-unstyled">
                        {% for hashtag in hashtags %}
                        <li class="col-sm">
                            <img src="/static/img/hashtag2.png" alt="" width="20" height="15">{{ hashtag }}
                            {% if hashtag.writer == request.user %}
                                <form action="{% url 'blog:tag-delete' pk=hashtag.pk %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" value="삭제" class="btn btn-outline-secondary btn-sm col-sm">
                                </form>
                            {% endif %}
                        </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <br>
                    <p>작성된 해시태그가 없습니다.</p>
                {% endif %}
        </div>


        <!-- 댓글 작성 화면 -->
        <h3><img src="/static/img/comment.png" alt="" width="30" height="30">Comment</h3>
        <div class="container">
            
            <!-- comments -->
            {% if comments %}
            <ul class="detail-comments">
                {% for comment in comments %}
                <li class="user-comment"><img src="/static/img/user.png" alt="" width="30" height="25"> {{ comment.content }} | {{ comment.created_at|date:"Y-m-d" }} | {{ comment.writer }}
                    {% if comment.writer == request.user %}
                    <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="삭제" class='btn btn-outline-secondary btn-sm'>
                    </form>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>코멘트가 없습니다.</p>
            {% endif %}

            <!-- 댓글 작성 -->
            <form class="comment-form" action="{% url 'blog:cm-write' pk=post_id %}" method="post">
                {% csrf_token %}
                {% if comment_form.errors %}
                    {% with form=comment_form %}
                        {% include 'blog/form_error.html' %}
                    {% endwith %}
                {% else %}
                    {{ comment_form.content }}
                {% endif %}
                <input class="btn btn-outline-secondary btn-sm" type="submit" value="등록">
            </form>
        </div>
    


{% endblock %}

projects/blog/templates/blog/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="write-title">게시글 수정 페이지</h2>
    <form class="write-form" action="{% url 'blog:edit' pk=post.pk %}" method="post">
        <input type="submit" value='등록' class="post-write-button">
        <br>
        {% csrf_token %}
        {{ form.as_p }}
    </form>
{% endblock %}

projects/blog/templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="write-title">게시글 작성 페이지</h2>
    <form class="write-form" action="{% url 'blog:write' %}" method="post" enctype="multipart/form-data">
        <button class="post-write-button mb-2">등록</button>
            <div class="form-group">
                <label for="imgfile">이미지 : </label>
                <input type="file" class="form-control" name="imgfile" id="imgfile">
            </div>
            <br>
    {% csrf_token %}
    {{ form.as_p }}
    </form>
{% endblock %}

projects/blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% block content %}

<h1 class="post-title pb-2">게시판 페이지</h1>

<div class="post-top">

    <!-- 게시글 수 세기 -->
    <div class="post-count">
        {% if post_obj.count > 0 %}
        <p><strong>{{ post_obj.count }}개</strong>의 게시글이 있습니다.</p>
        {% else %}
        <p><strong>0개</strong>의 게시글이 있습니다.</p>
        {% endif %}
    </div>

    <!-- 태그 검색 -->
    <div class="search-tag">
        <form id="search-form" action="" method="get">
            <input id="search-input" type="text" placeholder="태그를 검색해주세요"/>
            <input type="submit" value="search">
        </form>
            <script>
                const form = document.querySelector('#search-form')
                const input = document.querySelector('#search-input')
                input.addEventListener('input', () => {
                    inputValue = input.value
                    s = `{% url 'blog:post-search' tag="value"%}`
                    console.log(s)
                    s = s.replace('value', inputValue)
                    console.log(s)
                    form.action = s
                });
            </script>
    </div>
</div>


    <!-- 게시글 보이기 -->
    <table class="table table-bordered mt-2">
        <thead class="table-light">
                {% if posts %}
                <tr>
                    <td>No</td>
                    <td>제목</td>
                    <td>작성자</td>
                    <td>작성일시</td>
                    <td>이미지 유/무</td>
                    <td>조회수</td>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <tr>
                    <td>
                        {{ post.id }}
                    </td>
                    <td>
                        <a href="{% url 'blog:detail' pk=post.pk %}" class="btn">{{ post.title }}</a>
                        <!-- 댓글 개수 표시 -->
                        {% if post.comment_set.count > 0 %}
                        <span class="text-success small ml-2">{{ post.comment_set.count }}</span>
                        {% endif %}
                    </td>
                    <td><a href="{% url 'blog:detail' pk=post.pk %}" class="btn">{{ post.writer }}</a></td>
                    <td><a href="{% url 'blog:detail' pk=post.pk %}" class="btn">{{ post.created_at|date:"Y-m-d" }}</a></td>
                    <td>
                        {% if post.imgfile %}
                        <span class="badge bg-secondary py-1">O</span>
                        {% else %}
                        <span class="badge bg-warning py-1">X</span>
                        {% endif %}
                    </td>
                    <td>{{ post.hit }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
    <p>작성된 게시글이 없습니다.</p>
    {% endif %}

    <!-- 목록 하단 글작성 버튼 -->
    <div>
        <a href="{% url 'blog:write' %}" class="btn btn-outline-secondary float-end">글작성</a>
    </div>
</div>



<!-- 페이징처리시작 -->
    <ul class="pagination justify-content-center" id="page_button">
        <!-- 이전페이지 -->
        {% if posts.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.previous_page_number }}"><img src="/static/img/prev.png" width="30" height="24" alt="이전"></a>
        </li>   
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><img src="/static/img/prev.png" width="30" height="24" alt="이전"></a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in posts.paginator.page_range %}
        {% if page_number >= posts.number|add:-5 and page_number <= posts.number|add:5 %}
            {% if page_number == posts.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if posts.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.next_page_number }}"><img src="/static/img/next.png" width="30" height="24" alt="다음"></a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                <img src="/static/img/next.png" width="30" height="24" alt="다음"></a>
        </li>
        {% endif %}
    </ul>

<!-- 페이징처리 끝 -->

{% endblock %}